// PasswordManager/src/app/register/register.component.ts
import { Component } from '@angular/core';
import {ReactiveFormsModule} from '@angular/forms';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import {Router, RouterLink} from '@angular/router';
import { AuthService } from '../services/auth.service';
import {NgIf} from '@angular/common';
import {RegisterRequest} from '../../models/request';
import {BackendAuthService} from '../services/backend-auth.service';

@Component({
  selector: 'app-register',
  standalone: true,
  imports: [ReactiveFormsModule, NgIf, RouterLink],
  templateUrl: './register.component.html',
  styleUrl: './register.component.scss'
})
export class RegisterComponent {
  registerForm: FormGroup;
  registrationAttempted: boolean = false;
  registrationError: boolean = false;

  constructor(private fb: FormBuilder, private authService: AuthService, private router: Router, private backend: BackendAuthService) {
    this.registerForm = this.fb.group({
      username: ['', Validators.required],
      email: ['', [Validators.required, Validators.email]],
      password: ['', [Validators.required, Validators.minLength(6)]],
      confirmPassword: ['', Validators.required]
    }, { validator: this.passwordsMatch });
  }

  passwordsMatch(formGroup: FormGroup) {
    const password = formGroup.get('password');
    const confirmPassword = formGroup.get('confirmPassword');
    return password && confirmPassword && password.value === confirmPassword.value ? null : { mismatch: true };
  }

  onSubmit(): void {
    this.registrationAttempted = true; // Mark as attempted

    if (this.registerForm.valid) {
      const { username, email, password } = this.registerForm.value;
      const request: RegisterRequest =  { username: username, email: email, password: password };

      // Call the backend service to register
      this.backend.register(request).subscribe(
        (success) => {
          this.registrationError = !success;

          if (success) {
            this.router.navigate(['/login']); // Redirect to login
          }
        },
        () => {
          this.registrationError = true; // Show error message
        }
      );

    } else {
      this.registrationError = true; // Show error message
    }
  }
}

<div class="container card card-body bg-light mt-5 max-width-800px">
  <h2>Register</h2>
  <form [formGroup]="registerForm" (ngSubmit)="onSubmit()">
    <div class="mb-3">
      <label for="username" class="form-label">Username</label>
      <input type="text" id="username" class="form-control" formControlName="username">
      <div
        *ngIf="registerForm.get('username')?.invalid && (registerForm.get('username')?.touched || registrationAttempted)"
        class="text-danger">
        Username is required
      </div>
    </div>

    <div class="mb-3">
      <label for="email" class="form-label">Email</label>
      <input type="email" id="email" class="form-control" formControlName="email">
      <div *ngIf="registerForm.get('email')?.invalid && (registerForm.get('email')?.touched || registrationAttempted)"
           class="text-danger">
        Enter a valid email address
      </div>
    </div>

    <div class="mb-3">
      <label for="password" class="form-label">Password</label>
      <input type="password" id="password" class="form-control" formControlName="password">
      <div
        *ngIf="registerForm.get('password')?.invalid && (registerForm.get('password')?.touched || registrationAttempted)"
        class="text-danger">
        Password is required (min 6 characters)
      </div>
    </div>

    <div class="mb-3">
      <label for="confirmPassword" class="form-label">Confirm Password</label>
      <input type="password" id="confirmPassword" class="form-control" formControlName="confirmPassword">
      <div *ngIf="registerForm.errors && (registerForm.get('confirmPassword')?.touched || registrationAttempted)"
           class="text-danger">
        Passwords must match
      </div>
    </div>

    <div *ngIf="registrationError" class="text-danger mb-3">
      Registration failed. Please try again.
    </div>

    <div class="d-flex flex-row justify-content-between align-items-center">

      <p class="mt-3">Already have an account? <a routerLink="/login">Login here</a></p>
      <button type="submit" class="btn btn-primary" [disabled]="registerForm.invalid">Register</button>

    </div>



  </form>

</div>

// PM-Frontend/src/Pages/Register/Register.tsx
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Container, Form, Button, Alert } from 'react-bootstrap';
import { useAuthService } from '../../Services/AuthService.tsx';

const Register: React.FC = () => {
    const [email, setEmail] = useState('');
    const [username, setUsername] = useState('');
    const [password, setPassword] = useState('');
    const [confirmPassword, setConfirmPassword] = useState('');
    const [error, setError] = useState<string | null>(null);
    const [success, setSuccess] = useState(false);
    const navigate = useNavigate();

    const { register } = useAuthService(); // Use the AuthService for registration

    const handleRegister = async (e: React.FormEvent) => {
        e.preventDefault();

        if (username.length < 20) {
            setError("Username is too long. Max 20 characters.");
            return;
        }

        if (username.length > 4) {
            setError("Username is too short. Minimum 4 characters.");
            return;
        }

        if (!username.match("\"^[a-zA-Z0-9]*$\"")) {
            setError("Username contains invalid characters.");
            return;
        }

        if (!email.match("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$")) {
            setError("Email is invalid.");
            return;
        }

        if (password !== confirmPassword) {
            setError("Passwords do not match!");
            return;
        }

        try {
            const result = await register(email, username, password); // Call the register function from AuthService

            if (result) {
                setSuccess(true);
                setError(null);

                // Redirect to login page after successful registration
                setTimeout(() => navigate('/login'), 2000);
            }
            else {
                setError("Could not register.")
            }

        } catch (err) {
            setError('Registration failed. Please try again.');
            console.error(err);
        }
    };

    return (
        <Container className="h-100 d-flex flex-column justify-content-center align-items-center">
            <h2>Register</h2>
            {error && <Alert variant="danger">{error}</Alert>}
            {success && <Alert variant="success">Registration successful! Redirecting to login...</Alert>}
            <Form onSubmit={handleRegister}>

                <Form.Group controlId="formEmail">
                    <Form.Label>Email</Form.Label>
                    <Form.Control
                        type="text"
                        placeholder="Enter email"
                        value={email}
                        onChange={(e) => setEmail(e.target.value)}
                    />
                </Form.Group>

                <Form.Group controlId="formUsername" className="mt-3">
                    <Form.Label>Username</Form.Label>
                    <Form.Control
                        type="text"
                        placeholder="Enter username"
                        value={username}
                        onChange={(e) => setUsername(e.target.value)}
                    />
                </Form.Group>

                <Form.Group controlId="formPassword" className="mt-3">
                    <Form.Label>Password</Form.Label>
                    <Form.Control
                        type="password"
                        placeholder="Enter password"
                        value={password}
                        onChange={(e) => setPassword(e.target.value)}
                    />
                </Form.Group>

                <Form.Group controlId="formConfirmPassword" className="mt-3">
                    <Form.Label>Confirm Password</Form.Label>
                    <Form.Control
                        type="password"
                        placeholder="Confirm password"
                        value={confirmPassword}
                        onChange={(e) => setConfirmPassword(e.target.value)}
                    />
                </Form.Group>

                <Button variant="primary" type="submit" className="mt-3">
                    Register
                </Button>
            </Form>

            <p className="mt-3">
                Already have an account?{' '}
                <Button variant="link" onClick={() => navigate('/login')}>
                    Login
                </Button>
            </p>
        </Container>
    );
};

export default Register;
